remote_theme: "mmistakes/minimal-mistakes@4.28.1"

plugins:
  - jekyll-include-cache

title: "Eimi Oda"
url: "https://eimioda.github.io"
baseurl: ""

author:
  name: "Eimi Oda"
  
# Navigation
main:
  - title: "About"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Baseball Analytics"
    url: "/baseball/"
